music = {
  "fanfare.wav",
  "happy.wav",
  "mendelssohn.wav",
  "theme.wav",
  "marching.wav",
  "dungeon.wav",
  "death.wav",
  "crystal.wav",
  "get_crystal.wav",
  "adagio.wav",
  "c_major_piece.wav",
  "later_folia.wav",
  "sakura.wav",
  "early_folia.wav",
  "handel.wav",
}
